name: woke
summary: Detect non-inclusive language in your source code 
description: |
      Creating an inclusive work environment is imperative to a healthy,
      supportive, and productive culture, and an environment where everyone
      feels welcome and included. woke is a text file analysis tool that finds
      places within your source code that contain non-inclusive language and
      suggests replacing them with more inclusive alternatives.
adopt-info: woke
grade: stable
base: core20
architectures:
  - build-on: [arm64, armhf, amd64]

confinement: strict

plugs:
  dot-config-woke:
    interface: personal-files
    read:
      - $HOME/.config/woke.yaml
      - $HOME/.woke.yaml

apps:
  woke:
    command: bin/woke
    plugs:
      - home
      - dot-config-woke
      - network

parts:
  woke:
    plugin: go
    source-type: git
    source: https://github.com/get-woke/woke 
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version \
      "$(git describe --long --tags --always --match=v*.*.* | sed 's/v//')"
    
